services:
  postgresql:
    image: postgres:15
    container_name: yahalom-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_test

volumes:
  pgdata:
