{{- $releaseName := .Release.Name -}}
{{- $chartName := include "yahalom-gateway.name" . -}}
{{- $cloudProviderFlavor := include "yahalom-gateway.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "yahalom-gateway.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "yahalom-gateway.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ printf "%s-%s" $releaseName $chartName }}
    {{- include "yahalom-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
