apiVersion: v2
name: yahalom-gateway
description: A Helm chart for yahalom-gateway service
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: yahalom-gateway
    version: 0.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/
    alias: yahalom-gateway
